name: PR Requirements (Labels, Assignees, Title)

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, assigned, unassigned, edited]

jobs:
  pr_lint:
    name: PR Lint
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: morrisoncole/pr-lint-action@v1.7.1
        with:
          repo-token: '${{ secrets.GH_TOKEN }}'
          title-regex: "^(chore|bug|fix|feat|refactor|perf|style|doc|test|release|build|ops)(?:\\([A-Z]{1,}-[0-9]{1,}\\))?: .[A-Za-z]{1}.{1,}$"
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-request-changes: true
          on-succeeded-regex-dismiss-review-comment: '✅ **Success:** PR title format is valid! 🎉'
          on-failed-regex-comment: |
            > [!CAUTION] 
            > ⛔ **The PR title format does not meet the required guidelines**.

            > [!TIP]
            > Please refer to [this](https://github.com/go-illa/illa-rails/wiki/PR-Title-Format-Guidelines%F0%9F%93%91) guide🎯 for instructions on how to format the PR title according to the guidelines.
  pr_rules:
    name: PR Rules
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Authenticate GitHub CLI
        run: gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Check for Labels, Assignee, and PR Title
        run: |
          REPO="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_TITLE="${{ github.event.pull_request.title }}"

          LABEL_COUNT=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json labels --jq '.labels | length')
          ASSIGNEE_COUNT=$(gh pr view "$PR_NUMBER" --repo "$REPO" --json assignees --jq '.assignees | length')

          echo "🔍 Checking PR #$PR_NUMBER"
          echo "📌 Label Count: $LABEL_COUNT"
          echo "👤 Assignee Count: $ASSIGNEE_COUNT"
          echo "📝 PR Title: $PR_TITLE"

          ERROR_MESSAGE=""

          # Enforce Labels & Assignee
          if [[ "$LABEL_COUNT" -eq 0 ]]; then
            ERROR_MESSAGE+="❌ **Error:** This PR must have at least **one label.**\n"
          fi

          if [[ "$ASSIGNEE_COUNT" -eq 0 ]]; then
            ERROR_MESSAGE+="❌ **Error:** This PR must have at least **one assignee.**\n"
          fi

          # Enforce PR Title Format
          PR_TITLE_REGEX="^(chore|bug|fix|feat|refactor|perf|style|doc|test|release|build|ops)(\([A-Z]{1,}-[0-9]{1,}\))?: .[A-Za-z]{1}.{1,}$"
          if [[ ! "$PR_TITLE" =~ $PR_TITLE_REGEX ]]; then
            ERROR_MESSAGE+="❌ **Error:** PR title is invalid. Please update it to match the required format.\n"
          fi

          # Print errors instead of commenting on PR
          if [[ -n "$ERROR_MESSAGE" ]]; then
            echo -e "🚨 Issues found in PR:\n$ERROR_MESSAGE"
            exit 1
          else
            echo "✅ PR meets all requirements!"
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
