name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Security Scan
        uses: github/codeql-action/analyze@v2
        with:
          category: "security"
