name: Auto Assign PR to Creator

on:
  pull_request:
    types: [opened]

jobs:
  auto_assign:
    name: Auto Assign PR
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Add Empty Commit with Message
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          REPO="${{ github.repository }}"
          git config --global user.email "githubilla@illa.com.eg"
          git config --global user.name "ILLA TECH"
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/$REPO.git
          cd $(basename "$REPO")
          git checkout "$BRANCH_NAME"
          git commit --allow-empty -m "CodeRabbit Trigger"
          git push origin "$BRANCH_NAME"

      - name: Authenticate GitHub CLI
        run: gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Assign PR to the Creator
        id: assign_pr
        run: |
          REPO="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          CREATOR="${{ github.event.pull_request.user.login }}"

          if gh pr edit $PR_NUMBER --repo "$REPO" --add-assignee "$CREATOR"; then
            echo "ASSIGNMENT_SUCCESS=true" >> $GITHUB_ENV
          else
            echo "ASSIGNMENT_SUCCESS=false" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Wait for 30 seconds Before Commenting
        run: sleep 30

      - name: Comment on PR
        run: |
          REPO="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"

          gh pr comment $PR_NUMBER --repo "$REPO" --body "@coderabbitai full review"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
